-- ============================================================
-- WINDOW FUNCTIONS PRACTICE
-- ============================================================

-- ============================================================
-- 1. OVER()
-- Find the total sales across all orders.
-- ============================================================

SELECT
    customer_id,
    order_id,
    SUM(total_price) OVER() AS total_sales
FROM orders;


-- ============================================================
-- 2. PARTITION BY
-- Find total sales generated by each customer.
-- ============================================================

SELECT
    customer_id,
    order_id,
    SUM(total_price) OVER(PARTITION BY customer_id) AS customer_total_sales
FROM orders;


-- ============================================================
-- 3. COUNT() OVER()
-- Find the total number of orders placed by each customer.
-- ============================================================

SELECT
    customer_id,
    order_id,
    COUNT(order_id) OVER(PARTITION BY customer_id) AS total_orders
FROM orders;


-- ============================================================
-- 4. ROW_NUMBER()
-- Assign a sequential number to each customer's orders
-- based on the order date.
-- ============================================================

SELECT
    customer_id,
    order_id,
    order_date,
    ROW_NUMBER() OVER(
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS order_number
FROM orders;


-- ============================================================
-- 5. RANK()
-- Rank orders based on total price from highest to lowest.
-- ============================================================

SELECT
    order_id,
    customer_id,
    total_price,
    RANK() OVER(
        ORDER BY total_price DESC
    ) AS sales_rank
FROM orders;


-- ============================================================
-- 6. RUNNING TOTAL
-- Calculate cumulative sales over time.
-- ============================================================

SELECT
    order_date,
    total_price,
    SUM(total_price) OVER(
        ORDER BY order_date
    ) AS running_total
FROM orders;


-- ============================================================
-- 7. CUSTOMER-WISE RUNNING TOTAL
-- Calculate cumulative sales for each customer.
-- ============================================================

SELECT
    customer_id,
    order_date,
    total_price,
    SUM(total_price) OVER(
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS customer_running_total
FROM orders;


-- ============================================================
-- 8. LAG()
-- Compare each order's sales with the previous order.
-- ============================================================

SELECT
    order_id,
    customer_id,
    order_date,
    total_price,
    LAG(total_price) OVER(
        ORDER BY order_date
    ) AS previous_order_sales
FROM orders;


-- ============================================================
-- 9. LEAD()
-- Compare each order's sales with the next order.
-- ============================================================

SELECT
    order_id,
    customer_id,
    order_date,
    total_price,
    LEAD(total_price) OVER(
        ORDER BY order_date
    ) AS next_order_sales
FROM orders;